// Migrações incrementais sobre o esquema base SQLite ou server/schema.sql (PostgreSQL).
// Uma falha desfaz todas as migrações pendentes desta execução. Nunca remove dados.
import { alinharIntegridade } from './migration-integridade.js';
import { sqlSeguranca } from './seguranca-supabase.js';
const MIGRACOES = [
  {
    id: 1,
    nome: 'acoes_arquivadas',
    async aplicar(db) {
      const colunas = db.isPg
        ? await db.prepare("select column_name as nome from information_schema.columns where table_schema = current_schema() and table_name = 'acoes'").all()
        : (await db.prepare('pragma table_info(acoes)').all()).map(c => ({ nome: c.name }));
      if (!colunas.length) throw new Error('Esquema base ausente. Provisione server/schema.sql antes de migrar PostgreSQL.');
      if (!colunas.some(c => c.nome === 'arquivada')) {
        await db.exec('alter table acoes add column arquivada integer not null default 0');
      }
    },
  },
  {
    id: 2,
    nome: 'unicidade_pedidos_e_reunioes',
    async aplicar(db) {
      const duplicados = await db.prepare("select acao_id from pedidos_prazo where status = 'pendente' group by acao_id having count(*) > 1").all();
      if (duplicados.length) throw new Error(`Migração interrompida: pedidos pendentes duplicados nas ações ${duplicados.map(r => r.acao_id).join(', ')}. Revise os registros antes de tentar novamente.`);
      const abertas = await db.prepare("select id from reunioes where status = 'em_andamento' order by id").all();
      if (abertas.length > 1) throw new Error(`Migração interrompida: reuniões simultâneas em andamento (${abertas.map(r => r.id).join(', ')}). Revise os registros antes de tentar novamente.`);
      await db.exec("create unique index uq_pedido_pendente_acao on pedidos_prazo(acao_id) where status = 'pendente'");
      await db.exec("create unique index uq_reuniao_em_andamento on reunioes(status) where status = 'em_andamento'");
    },
  },
  { id: 3, nome: 'integridade_referencial', aplicar: alinharIntegridade },
  {
    id: 4, nome: 'identidade_institucional',
    async aplicar(db) {
      if (db.isPg && (await db.prepare('select current_schema() as nome').get()).nome !== 'public') {
        throw new Error('A migração de permissões exige o esquema public. Revise o search_path antes de executar.');
      }
      await db.exec(`create table if not exists auth_identidades (
        id integer primary key ${db.isPg ? 'generated by default as identity' : ''},
        usuario_id integer not null unique references usuarios(id),
        tenant_id text not null, object_id text not null,
        unique (tenant_id, object_id)
      );
      create table if not exists auth_sessoes (
        id text primary key, identidade_id integer not null references auth_identidades(id),
        csrf text not null, expira_em integer not null
      );
      create index if not exists idx_auth_sessoes_expira on auth_sessoes(expira_em);
      create table if not exists auth_fluxos (
        id text primary key, nonce text not null, verifier text not null, expira_em integer not null
      );
      create index if not exists idx_auth_fluxos_expira on auth_fluxos(expira_em);`);
      if (db.isPg) await db.exec(sqlSeguranca({ transacao: false }));
    },
  },
  {
    id: 5, nome: 'login_email_senha',
    async aplicar(db) {
      await db.exec(`create table if not exists auth_contas (
        id integer primary key ${db.isPg ? 'generated by default as identity' : ''},
        usuario_id integer not null unique references usuarios(id),
        projeto text not null, subject text not null, unique (projeto, subject)
      );
      create table if not exists auth_sessoes_senha (
        id text primary key, conta_id integer not null references auth_contas(id),
        csrf text not null, expira_em integer not null
      );
      create index if not exists idx_auth_senha_expira on auth_sessoes_senha(expira_em);
      create table if not exists auth_tentativas (
        id text primary key, janela integer not null, tentativas integer not null
      );
      create index if not exists idx_auth_tentativas_janela on auth_tentativas(janela);`);
      if (db.isPg) await db.exec(sqlSeguranca({ transacao: false }));
    },
  },
  {
    id: 6, nome: 'autoria_acoes',
    async aplicar(db) {
      const colunas = db.isPg
        ? await db.prepare("select column_name as nome from information_schema.columns where table_schema=current_schema() and table_name='acoes'").all()
        : (await db.prepare('pragma table_info(acoes)').all()).map(c=>({nome:c.name}));
      if (!colunas.some(c=>c.nome==='criado_por')) await db.exec('alter table acoes add column criado_por integer references usuarios(id)');
      // Diretrizes registram autoria estruturada. Ações legadas sem essa origem
      // permanecem sem autor conhecido; comentários livres não concedem permissão.
      await db.exec('update acoes set criado_por=(select criado_por from diretrizes where diretrizes.id=acoes.diretriz_id) where criado_por is null and diretriz_id is not null');
      if (db.isPg) await db.exec(sqlSeguranca({ transacao: false }));
    },
  },
];

async function registros(db) {
  return db.prepare('select id, nome from schema_migrations order by id').all();
}

function conferir(aplicadas) {
  for (const registro of aplicadas) {
    if (!MIGRACOES.some(m => m.id === registro.id && m.nome === registro.nome)) {
      throw new Error(`Migração ${registro.id} incompatível com esta versão da aplicação.`);
    }
  }
}

export async function aplicarMigracoes(db) {
  return db.transaction(async () => {
    // Chave exclusiva da evolução do esquema; liberada no commit/rollback.
    if (db.isPg) await db.prepare('select pg_advisory_xact_lock(7319, 1)').get();
    await db.exec('create table if not exists schema_migrations (id integer primary key, nome text not null, aplicada_em text not null)');
    const aplicadas = await registros(db);
    conferir(aplicadas);
    const novas = [];
    for (const migracao of MIGRACOES) {
      if (aplicadas.some(m => m.id === migracao.id)) continue;
      await migracao.aplicar(db);
      await db.prepare('insert into schema_migrations (id, nome, aplicada_em) values (?, ?, ?)')
        .run(migracao.id, migracao.nome, new Date().toISOString());
      novas.push(migracao.id);
    }
    return novas;
  }, { rebuildForeignKeys: true });
}

/** PostgreSQL em execução só verifica o esquema; a implantação aplica migrações separadamente. */
export async function verificarMigracoes(db) {
  let aplicadas;
  try { aplicadas = await registros(db); }
  catch (err) {
    if (err.code === '42P01' || (err.code === 'SQLITE_ERROR' && /no such table: schema_migrations/.test(err.message))) {
      throw new Error('Migrações pendentes. Execute npm run migrate com o destino explícito antes de iniciar.');
    }
    throw err;
  }
  conferir(aplicadas);
  if (MIGRACOES.some(m => !aplicadas.some(a => a.id === m.id))) {
    throw new Error('Migrações pendentes. Execute npm run migrate com o destino explícito antes de iniciar.');
  }
}
