-- Schema SGA/Agilis para Supabase (PostgreSQL)

-- 1. Seções
create table if not exists secoes (
  id integer primary key generated by default as identity,
  nome text not null,
  sigla text,
  tipo text not null check (tipo in ('centro','coordenacao','subsecao')),
  pai_id integer references secoes(id),
  ordem integer not null default 0,
  ativa integer not null default 1,
  chefe_id integer,
  criada_em text not null
);

-- 2. Usuários
create table if not exists usuarios (
  id integer primary key generated by default as identity,
  nome text not null,
  email text,
  perfil text not null check (perfil in ('diretor','chefe','apoio')),
  secao_id integer references secoes(id),
  ativo integer not null default 1
);

-- Adiciona chave estrangeira de chefe após criação de usuarios (adiável para permitir inserções em transação)
alter table secoes drop constraint if exists fk_secoes_chefe;
alter table secoes add constraint fk_secoes_chefe foreign key (chefe_id) references usuarios(id) deferrable initially deferred;

-- 3. Diretrizes
create table if not exists diretrizes (
  id integer primary key generated by default as identity,
  titulo text not null,
  detalhe text,
  destino text not null check (destino in ('todos','especificos')),
  prazo text not null,
  prioridade text not null default 'media',
  criado_por integer references usuarios(id),
  criado_em text not null,
  reuniao_id integer
);

-- 4. Ações
create table if not exists acoes (
  id integer primary key generated by default as identity,
  diretriz_id integer references diretrizes(id),
  secao_id integer not null references secoes(id),
  acao_pai_id integer references acoes(id),
  titulo text not null,
  detalhe text,
  status text not null default 'a_fazer',
  prazo text not null,
  prazo_original text not null,
  prioridade text not null default 'media',
  interna integer not null default 0,
  compartilhada integer not null default 0,
  encerrada integer not null default 0,
  arquivada integer not null default 0,
  concluida_em text,
  criada_em text not null
);

create index if not exists idx_acoes_secao         on acoes(secao_id);
create index if not exists idx_acoes_status        on acoes(status);
create index if not exists idx_acoes_encerrada     on acoes(encerrada);
create index if not exists idx_acoes_arquivada     on acoes(arquivada);
create index if not exists idx_acoes_prazo         on acoes(prazo);
create index if not exists idx_acoes_diretriz      on acoes(diretriz_id);
-- Índice composto para o filtro mais comum: ações abertas por seção
create index if not exists idx_acoes_secao_status  on acoes(secao_id, encerrada, status);

-- 5. Comentários da Ação
create table if not exists acao_comentarios (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id) on delete cascade,
  usuario_id integer references usuarios(id),
  texto text not null,
  criado_em text not null
);

-- 6. Apontamento de Tempo
create table if not exists tempo (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id) on delete cascade,
  usuario_id integer references usuarios(id),
  data text not null,
  minutos integer not null check (minutos > 0),
  criado_em text not null
);

-- 7. Pedidos de Prazo
create table if not exists pedidos_prazo (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id) on delete cascade,
  usuario_id integer references usuarios(id),
  prazo_atual text not null,
  novo_prazo text not null,
  justificativa text not null,
  status text not null default 'pendente' check (status in ('pendente','aprovado','recusado')),
  criado_em text not null,
  decidido_em text,
  decidido_por integer references usuarios(id),
  reuniao_id integer
);

create index if not exists idx_pedidos_status    on pedidos_prazo(status);
create index if not exists idx_pedidos_acao      on pedidos_prazo(acao_id);

-- 8. Atualizações Semanais
create table if not exists atualizacoes (
  id integer primary key generated by default as identity,
  secao_id integer not null references secoes(id),
  semana text not null,
  versao integer not null,
  feito text not null default '{}',
  proximo text not null default '[]',
  impedimentos text not null default '[]',
  critico integer not null default 0,
  apoio text,
  usuario_id integer references usuarios(id),
  enviada_em text not null,
  unique (secao_id, semana, versao)
);

create index if not exists idx_atualizacoes_secao_semana  on atualizacoes(secao_id, semana);
create index if not exists idx_atualizacoes_semana_versao on atualizacoes(secao_id, semana, versao desc);

-- 9. Combinados
create table if not exists combinados (
  id integer primary key generated by default as identity,
  texto text not null,
  ordem integer not null default 0,
  ativo integer not null default 1,
  arquivado integer not null default 0,
  criado_por integer references usuarios(id),
  criado_em text not null,
  alterado_em text not null
);

-- 10. Configuração
create table if not exists config (
  chave text primary key,
  valor text not null
);

-- 11. Reuniões
create table if not exists reunioes (
  id integer primary key generated by default as identity,
  data text not null,
  semana text not null,
  iniciada_em text not null,
  encerrada_em text,
  status text not null default 'em_andamento' check (status in ('em_andamento','rascunho','enviada')),
  combinados_snapshot text not null default '[]',
  ata_texto text,
  enviada_em text,
  criada_por integer references usuarios(id)
);

create index if not exists idx_tempo_acao         on tempo(acao_id);
create index if not exists idx_tempo_data          on tempo(data);
create index if not exists idx_comentarios_acao    on acao_comentarios(acao_id);

-- 12. Decisões da Reunião
create table if not exists decisoes (
  id integer primary key generated by default as identity,
  reuniao_id integer not null references reunioes(id) on delete cascade,
  secao_id integer references secoes(id),
  texto text not null,
  criada_em text not null,
  criada_por integer references usuarios(id)
);

create index if not exists idx_decisoes_reuniao   on decisoes(reuniao_id);

-- Função recursiva para obter ids da subárvore de seções
create or replace function subarvore(root_id integer)
returns table(id integer) as $$
  with recursive t(id) as (
    select root_id
    union all
    select s.id from secoes s join t on s.pai_id = t.id
  )
  select id from t;
$$ language sql stable;
