-- =====================================================================
-- SGA/Agilis: criação completa do banco em um projeto Supabase NOVO e VAZIO.
--
-- Como usar: Supabase → SQL Editor → New query → cole este arquivo → Run.
-- Resultado: o mesmo esquema que server/schema.sql + migrações 1 a 8 produzem,
-- já com RLS ligada e acesso de anon/authenticated revogado, e com as versões
-- 1 a 8 registradas em schema_migrations (o servidor então não pede migração).
--
-- Consolidado de: server/schema.sql, server/migrations.js (versões 1 a 8) e
-- server/seguranca-supabase.sql. Se um destes mudar, atualize este arquivo
-- ou use o caminho oficial (schema.sql + npm run migrate -- --postgres).
--
-- Seguro contra execução em banco já provisionado: aborta sem alterar nada
-- se a tabela "secoes" ou "schema_migrations" já existir. Não apaga dados.
-- Tudo roda em uma transação: se algo falhar, nada é criado.
-- =====================================================================
begin;

do $verificacao$
begin
  if to_regclass('public.secoes') is not null or to_regclass('public.schema_migrations') is not null then
    raise exception 'O banco já contém objetos do Agilis. Este script serve apenas para um banco vazio; para atualizar um banco existente use npm run migrate -- --postgres.';
  end if;
end $verificacao$;

-- ---------------------------------------------------------------------
-- 1. Estrutura do negócio
-- ---------------------------------------------------------------------

create table secoes (
  id integer primary key generated by default as identity,
  nome text not null,
  sigla text,
  tipo text not null check (tipo in ('centro','coordenacao','subsecao')),
  pai_id integer references secoes(id),
  ordem integer not null default 0,
  ativa integer not null default 1,
  chefe_id integer,
  criada_em text not null
);

create table usuarios (
  id integer primary key generated by default as identity,
  nome text not null,
  email text,
  perfil text not null check (perfil in ('diretor','chefe','apoio','administrador')),
  secao_id integer references secoes(id),
  ativo integer not null default 1,
  trocar_senha integer not null default 0
);

-- FK adiada: permite cadastrar seção e chefe na mesma transação (migração 3).
alter table secoes add constraint fk_secoes_chefe
  foreign key (chefe_id) references usuarios(id) deferrable initially deferred;

create table diretrizes (
  id integer primary key generated by default as identity,
  titulo text not null,
  detalhe text,
  destino text not null check (destino in ('todos','especificos')),
  prazo text not null,
  prioridade text not null default 'media',
  criado_por integer references usuarios(id),
  criado_em text not null,
  reuniao_id integer
);

create table acoes (
  id integer primary key generated by default as identity,
  diretriz_id integer references diretrizes(id),
  secao_id integer not null references secoes(id),
  acao_pai_id integer references acoes(id),
  titulo text not null,
  detalhe text,
  status text not null default 'a_fazer',
  prazo text not null,
  prazo_original text not null,
  prioridade text not null default 'media',
  interna integer not null default 0,
  compartilhada integer not null default 0,
  encerrada integer not null default 0,
  arquivada integer not null default 0,
  concluida_em text,
  criada_em text not null,
  criado_por integer references usuarios(id)   -- migração 6
);

create index idx_acoes_secao        on acoes(secao_id);
create index idx_acoes_status       on acoes(status);
create index idx_acoes_encerrada    on acoes(encerrada);
create index idx_acoes_arquivada    on acoes(arquivada);
create index idx_acoes_prazo        on acoes(prazo);
create index idx_acoes_diretriz     on acoes(diretriz_id);
create index idx_acoes_secao_status on acoes(secao_id, encerrada, status);

create table acao_comentarios (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id),
  usuario_id integer references usuarios(id),
  texto text not null,
  criado_em text not null
);

create table tempo (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id),
  usuario_id integer references usuarios(id),
  data text not null,
  minutos integer not null check (minutos > 0),
  criado_em text not null
);

create table pedidos_prazo (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id),
  usuario_id integer references usuarios(id),
  prazo_atual text not null,
  novo_prazo text not null,
  justificativa text not null,
  status text not null default 'pendente' check (status in ('pendente','aprovado','recusado')),
  criado_em text not null,
  decidido_em text,
  decidido_por integer references usuarios(id),
  reuniao_id integer
);

create index idx_pedidos_status on pedidos_prazo(status);
create index idx_pedidos_acao   on pedidos_prazo(acao_id);
-- Migração 2: um único pedido pendente por ação.
create unique index uq_pedido_pendente_acao on pedidos_prazo(acao_id) where status = 'pendente';

create table atualizacoes (
  id integer primary key generated by default as identity,
  secao_id integer not null references secoes(id),
  semana text not null,
  versao integer not null,
  feito text not null default '{}',
  proximo text not null default '[]',
  impedimentos text not null default '[]',
  critico integer not null default 0,
  apoio text,
  usuario_id integer references usuarios(id),
  enviada_em text not null,
  unique (secao_id, semana, versao)
);

create index idx_atualizacoes_secao_semana  on atualizacoes(secao_id, semana);
create index idx_atualizacoes_semana_versao on atualizacoes(secao_id, semana, versao desc);

create table combinados (
  id integer primary key generated by default as identity,
  texto text not null,
  ordem integer not null default 0,
  ativo integer not null default 1,
  arquivado integer not null default 0,
  criado_por integer references usuarios(id),
  criado_em text not null,
  alterado_em text not null
);

create table config (
  chave text primary key,
  valor text not null
);

create table reunioes (
  id integer primary key generated by default as identity,
  data text not null,
  semana text not null,
  iniciada_em text not null,
  encerrada_em text,
  status text not null default 'em_andamento' check (status in ('em_andamento','rascunho','enviada')),
  combinados_snapshot text not null default '[]',
  ata_texto text,
  enviada_em text,
  criada_por integer references usuarios(id)
);

-- Migração 2: no máximo uma reunião em andamento.
create unique index uq_reuniao_em_andamento on reunioes(status) where status = 'em_andamento';

create index idx_tempo_acao       on tempo(acao_id);
create index idx_tempo_data       on tempo(data);
create index idx_comentarios_acao on acao_comentarios(acao_id);

create table decisoes (
  id integer primary key generated by default as identity,
  reuniao_id integer not null references reunioes(id),
  secao_id integer references secoes(id),
  texto text not null,
  criada_em text not null,
  criada_por integer references usuarios(id)
);

create index idx_decisoes_reuniao on decisoes(reuniao_id);

-- Ids da subárvore de seções (uma seção e todas as descendentes).
create or replace function subarvore(root_id integer)
returns table(id integer) as $$
  with recursive t(id) as (
    select root_id
    union all
    select s.id from secoes s join t on s.pai_id = t.id
  )
  select id from t;
$$ language sql stable;

-- ---------------------------------------------------------------------
-- 2. Login e sessão (migrações 4, 5 e 7)
-- ---------------------------------------------------------------------

-- Integração OAuth anterior (Entra); mantida vazia por compatibilidade.
create table auth_identidades (
  id integer primary key generated by default as identity,
  usuario_id integer not null unique references usuarios(id),
  tenant_id text not null,
  object_id text not null,
  unique (tenant_id, object_id)
);

create table auth_sessoes (
  id text primary key,
  identidade_id integer not null references auth_identidades(id),
  csrf text not null,
  expira_em integer not null
);
create index idx_auth_sessoes_expira on auth_sessoes(expira_em);

create table auth_fluxos (
  id text primary key,
  nonce text not null,
  verifier text not null,
  expira_em integer not null
);
create index idx_auth_fluxos_expira on auth_fluxos(expira_em);

-- Vínculo entre o usuário do Agilis e a conta do Supabase Auth (subject = UUID).
create table auth_contas (
  id integer primary key generated by default as identity,
  usuario_id integer not null unique references usuarios(id),
  projeto text not null,
  subject text not null,
  unique (projeto, subject)
);

create table auth_sessoes_senha (
  id text primary key,
  conta_id integer not null references auth_contas(id),
  csrf text not null,
  expira_em integer not null,
  criada_em integer not null default 0          -- migração 7
);
create index idx_auth_senha_expira on auth_sessoes_senha(expira_em);

create table auth_tentativas (
  id text primary key,
  janela integer not null,
  tentativas integer not null
);
create index idx_auth_tentativas_janela on auth_tentativas(janela);

-- ---------------------------------------------------------------------
-- 3. Controle de versões do esquema (o servidor confere estes registros)
-- ---------------------------------------------------------------------

create table schema_migrations (
  id integer primary key,
  nome text not null,
  aplicada_em text not null
);

insert into schema_migrations (id, nome, aplicada_em)
select v.id, v.nome, to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
from (values
  (1, 'acoes_arquivadas'),
  (2, 'unicidade_pedidos_e_reunioes'),
  (3, 'integridade_referencial'),
  (4, 'identidade_institucional'),
  (5, 'login_email_senha'),
  (6, 'autoria_acoes'),
  (7, 'sessao_deslizante'),
  (8, 'perfil_administrador')
) as v(id, nome);

-- ---------------------------------------------------------------------
-- 4. Segurança: RLS ligada e acesso direto (anon/authenticated) revogado.
--    Só o backend (papel postgres, dono das tabelas) acessa o banco.
--    Copiado de server/seguranca-supabase.sql.
-- ---------------------------------------------------------------------
do $seguranca$
declare tabela text; papel text; colunas text; sequencia text;
begin
  foreach tabela in array array['secoes', 'usuarios', 'diretrizes', 'acoes', 'acao_comentarios', 'tempo', 'pedidos_prazo', 'atualizacoes', 'combinados', 'config', 'reunioes', 'decisoes', 'schema_migrations', 'auth_identidades', 'auth_sessoes', 'auth_fluxos', 'auth_contas', 'auth_sessoes_senha', 'auth_tentativas'] loop
    if to_regclass(format('public.%I', tabela)) is null then continue; end if;
    execute format('alter table public.%I enable row level security', tabela);
    select string_agg(format('%I', column_name), ', ') into colunas from information_schema.columns
      where table_schema = 'public' and table_name = tabela;
    execute format('revoke all on table public.%I from public', tabela);
    execute format('revoke select (%s), insert (%s), update (%s), references (%s) on public.%I from public',
      colunas, colunas, colunas, colunas, tabela);
    foreach papel in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = papel) then
        execute format('revoke all on table public.%I from %I', tabela, papel);
        execute format('revoke select (%s), insert (%s), update (%s), references (%s) on public.%I from %I',
          colunas, colunas, colunas, colunas, tabela, papel);
      end if;
    end loop;
    if exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = tabela and column_name = 'id') then
      sequencia := pg_get_serial_sequence(format('public.%I', tabela), 'id');
      if sequencia is not null then
        execute format('revoke all on sequence %s from public', sequencia);
        foreach papel in array array['anon', 'authenticated'] loop
          if exists (select 1 from pg_roles where rolname = papel) then
            execute format('revoke all on sequence %s from %I', sequencia, papel);
          end if;
        end loop;
      end if;
    end if;
  end loop;
  if to_regprocedure('public.subarvore(integer)') is not null then
    revoke execute on function public.subarvore(integer) from public;
    foreach papel in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = papel) then
        execute format('revoke execute on function public.subarvore(integer) from %I', papel);
      end if;
    end loop;
  end if;
end $seguranca$;

-- ---------------------------------------------------------------------
-- 5. Conferência final (aborta e desfaz tudo se algo estiver errado)
-- ---------------------------------------------------------------------
do $conferencia$
declare sem_rls text;
begin
  select string_agg(c.relname, ', ') into sem_rls
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'r' and not c.relrowsecurity
     and c.relname in ('secoes','usuarios','diretrizes','acoes','acao_comentarios','tempo','pedidos_prazo',
       'atualizacoes','combinados','config','reunioes','decisoes','schema_migrations','auth_identidades',
       'auth_sessoes','auth_fluxos','auth_contas','auth_sessoes_senha','auth_tentativas');
  if sem_rls is not null then raise exception 'RLS não ligada em: %', sem_rls; end if;
  if (select count(*) from schema_migrations) <> 8 then raise exception 'Versões de esquema incompletas.'; end if;
end $conferencia$;

commit;

-- Confira: deve listar as 19 tabelas, todas com rls = true.
select c.relname as tabela, c.relrowsecurity as rls
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public' and c.relkind = 'r'
 order by c.relname;
