-- =====================================================================
-- Agilis: migração 10 (checklist_da_acao) para o Supabase, aplicada pelo SQL Editor.
-- Equivale a "npm run migrate -- --postgres" quando esta máquina não alcança o banco.
--
-- Pré-requisito: o banco está na versão 9. Se a 10 já estiver registrada, o script não altera nada.
-- Só acrescenta a tabela acao_checklist (e reaplica RLS/revogações). Não mexe em dados existentes.
-- IMPORTANTE: depois de rodar, o código ANTIGO da aplicação deixa de iniciar (versão 10 desconhecida).
-- Publique o código novo logo em seguida.
-- =====================================================================
begin;

do $verificacao$
begin
  if not exists (select 1 from schema_migrations where id = 9) then
    raise exception $$O banco não está na versão 9 (impedimentos_da_acao). Aplique as migrações anteriores antes.$$;
  end if;
end $verificacao$;

create table if not exists acao_checklist (
  id integer primary key generated by default as identity,
  acao_id integer not null references acoes(id),
  texto text not null,
  concluido integer not null default 0,
  ordem integer not null default 0,
  criado_em text not null,
  criado_por integer references usuarios(id),
  concluido_em text,
  concluido_por integer references usuarios(id)
);
create index if not exists idx_checklist_acao on acao_checklist(acao_id);

insert into schema_migrations (id, nome, aplicada_em)
values (10, $$checklist_da_acao$$, to_char(now() at time zone $$utc$$, $$YYYY-MM-DD"T"HH24:MI:SS.MS"Z"$$))
on conflict (id) do nothing;

-- RLS e revogações (o mesmo bloco de server/seguranca-supabase.sql)
do $seguranca$
declare tabela text; papel text; colunas text; sequencia text;
begin
  foreach tabela in array array['secoes', 'usuarios', 'diretrizes', 'acoes', 'acao_comentarios', 'tempo', 'pedidos_prazo', 'atualizacoes', 'combinados', 'config', 'reunioes', 'decisoes', 'impedimentos', 'acao_checklist', 'schema_migrations', 'auth_identidades', 'auth_sessoes', 'auth_fluxos', 'auth_contas', 'auth_sessoes_senha', 'auth_tentativas'] loop
    if to_regclass(format('public.%I', tabela)) is null then continue; end if;
    execute format('alter table public.%I enable row level security', tabela);
    select string_agg(format('%I', column_name), ', ') into colunas from information_schema.columns
      where table_schema = 'public' and table_name = tabela;
    execute format('revoke all on table public.%I from public', tabela);
    execute format('revoke select (%s), insert (%s), update (%s), references (%s) on public.%I from public',
      colunas, colunas, colunas, colunas, tabela);
    foreach papel in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = papel) then
        execute format('revoke all on table public.%I from %I', tabela, papel);
        execute format('revoke select (%s), insert (%s), update (%s), references (%s) on public.%I from %I',
          colunas, colunas, colunas, colunas, tabela, papel);
      end if;
    end loop;
    if exists(select 1 from information_schema.columns where table_schema = 'public' and table_name = tabela and column_name = 'id') then
      sequencia := pg_get_serial_sequence(format('public.%I', tabela), 'id');
      if sequencia is not null then
        execute format('revoke all on sequence %s from public', sequencia);
        foreach papel in array array['anon', 'authenticated'] loop
          if exists (select 1 from pg_roles where rolname = papel) then
            execute format('revoke all on sequence %s from %I', sequencia, papel);
          end if;
        end loop;
      end if;
    end if;
  end loop;
  if to_regprocedure('public.subarvore(integer)') is not null then
    revoke execute on function public.subarvore(integer) from public;
    foreach papel in array array['anon', 'authenticated'] loop
      if exists (select 1 from pg_roles where rolname = papel) then
        execute format('revoke execute on function public.subarvore(integer) from %I', papel);
      end if;
    end loop;
  end if;
end $seguranca$;

commit;

-- Confira: a versão 10 deve aparecer e "acao_checklist" deve ter rls = true.
select (select string_agg(id::text, $$, $$ order by id) from schema_migrations) as versoes,
       (select relrowsecurity from pg_class where oid = to_regclass($$public.acao_checklist$$)) as checklist_rls;
